name = "stdlib"
version = "0.1.0"
vale_version = "0.1.1"
author = "cardinal"
git = "https://github.com/ValeLang/stdlib"
readme = "README.md"
platforms = ["native"]

[[features]]
name = "command"
path = "src/command/"
requires = ["path"]

[[features.imports]]
command = "clang"
args = ["-c", "src/command/native/subprocess.c", "-I", "build", '-o", "build/subprocess.o"]
link_args = ["build/subprocess.o"]

[[features]]
name = "path"
path = "src/path/"

[[features.imports]]
command = "clang"
args = ["-c", "src/path/native/path.c", "-I", "build", "-o", "build/path.o"]
link_args = ["build/path.o"]
